USE EMPRESA
--DISTINCT
SELECT DISTINCT F.Salario
FROM FUNCIONARIO AS F;

SELECT * FROM FUNCIONARIO;

--WHERE
SELECT *
FROM FUNCIONARIO AS F
WHERE F.Pnome = 'João'
WHERE F.Salario <= 30000;

-- AND, OR NOT

SELECT *
FROM FUNCIONARIO AS F
WHERE F.Sexo = 'M'
AND F.Salario >= 30000;

--LIKE
SELECT *
FROM FUNCIONARIO AS F
WHERE F.Endereco LIKE '%São Paulo%'
OR F.Endereco LIKE '%Curitiba%'

SELECT *
FROM FUNCIONARIO AS F
WHERE  F.Endereco NOT LIKE '%São Paulo%' 

-- ORDER BY
SELECT *
FROM FUNCIONARIO AS F
ORDER BY F.Salario DESC;

-- VALORES NULL
SELECT *
FROM FUNCIONARIO AS F
WHERE F.Cpf_supervisor IS NULL; 


SELECT *
FROM FUNCIONARIO AS F
WHERE F.Cpf_supervisor IS NOT NULL; 

--TOP
SELECT TOP 3*
FROM FUNCIONARIO AS F
ORDER BY F.Salario ASC

-- Função min() max)

SELECT *
FROM FUNCIONARIO AS F;

SELECT MIN(F.Salario)
FROM FUNCIONARIO AS F;

SELECT *
FROM FUNCIONARIO AS F
WHERE F.Salario = (SELECT MIN(F.Salario)
					FROM FUNCIONARIO AS F)

--DECLARE
DECLARE @salario_min DECIMAL(10,2);
SELECT @salario_min = (SELECT MIN(F.Salario)
					FROM FUNCIONARIO AS F);

PRINT @salario_min;

SELECT *
FROM FUNCIONARIO AS F
WHERE F.Salario = @salario_min;

-- função COUNT, AVG E SUM

--COUNT
SELECT COUNT(F.Cpf)
FROM FUNCIONARIO AS F

SELECT COUNT(*)
FROM FUNCIONARIO;

SELECT COUNT(*)
FROM DEPENDENTE;

SELECT
	(SELECT COUNT(*) FROM FUNCIONARIO) AS Nr_Funcionarios,
	(SELECT COUNT(*) FROM DEPENDENTE) AS Nr_Dependentes,
	(SELECT COUNT(*) FROM FUNCIONARIO) + 
	(SELECT COUNT(*) FROM DEPENDENTE) AS TOTAL;


--AVG
SELECT AVG(F.Salario)
FROM FUNCIONARIO AS F;

--SUM
SELECT SUM(F.Salario)
FROM FUNCIONARIO AS F;

DECLARE @menor_salario DECIMAL(10,2)
DECLARE @media_salario DECIMAL(10,2)

SET @menor_salario = (SELECT MIN(Salario) FROM FUNCIONARIO);
SET @media_salario = (SELECT MIN(Salario) FROM FUNCIONARIO);

PRINT @media_salario - @menor_salario


--OPERADOR LIKE
SELECT *
FROM FUNCIONARIO AS F
WHERE YEAR(F.Datanasc) LIKE '1972';

-- Operador in

SELECT *
FROM FUNCIONARIO AS F
WHERE F.Salario IN (25000, 30000);



SELECT F.Pnome, TE.*
FROM FUNCIONARIO AS F
JOIN TRABALHA_EM AS TE ON F.Cpf = TE.Fcpf

DECLARE @cpf_fernando CHAR(11);

SET @cpf_fernando = (SELECT F.Cpf FROM FUNCIONARIO AS F WHERE F.Pnome = 'Fernando');



SELECT F.Pnome, TE.*
FROM FUNCIONARIO AS F
JOIN TRABALHA_EM AS TE ON F.Cpf = TE.Fcpf
WHERE TE.Pnr IN(SELECT Pnr FROM TRABALHA_EM WHERE Fcpf = @cpf_fernando)
AND TE.Horas IN (SELECT Horas FROM TRABALHA_EM WHERE Fcpf = @cpf_fernando)
AND NOT F.Pnome LIKE 'Fernando';